Hw/MIni_Project_1/weblog/blog/urls.py
from django.views.generic.base import TemplateView
from .views import *
from django.urls import path
from django.urls import path

from .views import *

urlpatterns = [
    path('all_post/', PostList.as_view(), name="post_list"),
    path('all_post/<slug:slug>/', post_detail, name='post_detail'),
    path('all_post/<int:pk>', CategoryDetail.as_view(), name='post-category'),
    path('tag/<int:pk>', TagDetail.as_view(), name='post-tag'),
    path('add_post/', add_post, name='add_post'),
    path('contact/', contact_form, name='contact'),
    path('signup/', signup, name='signup'),
    path('dashboard/', dashboard, name='dashboard'),
    path('all_post/<slug:slug>/edit/', edit_post, name='edit_post'),
    path('dashboard/new_post', add_post, name='new_post'),
    path('edit_profile/', UserEditView.as_view(), name='edit_profile'),
    path('password/', PasswordChangeView.as_view(),{'template_name': 'registration/password_change_form.html'} , name='password_change'),
    path('search/', search, name='search'),
    path('like/<slug:slug>', LikeView, name='like_post'),
    path('post/<slug:slug>', change_status_post, name='change_status_post'),
    path('like_cm/<int:id>', Like_comment, name='like_comment'),
    path('add/', add_category_tag, name='add-cat-tag'),
    path('delete/<int:id>', delete_c, name='delete-c'),
    path('delete-t/<int:id>', delete_t, name='delete-t'),
    path('edit-t/<int:id>', edit_t, name='edit-t'),
    path('edit-c/<int:id>', edit_c, name='edit-c'),
    path('delete-post/<slug:slug>', delete_post, name='delete-post'),







]

Hw/MIni_Project_1/weblog/weblog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('blog/', include('blog.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hw/MIni_Project_1/weblog/blog/models.py
import random

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import related
from django.db.models.signals import post_save
from django.urls import reverse
from django.template.defaultfilters import slugify

from .signals import save_comment


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status= 'PUB')

class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status= 'DRF')



class Category(models.Model):
    name = models.CharField("name of category", max_length=50)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse("post-category", kwargs={"pk": self.pk})


class Tag(models.Model):
    name = models.CharField("name of tag start with #", max_length=50)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse("post-category", kwargs={"pk": self.pk})


# define a function to add some digit to end of slug >>>> for uniqueness
def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slug + str(random.randint(0, 12000))
    return unique_slug


class Post(models.Model):
    PUBLISHED= 'PUB'
    DRAFT= 'DRF'
    STATUS= [
        (PUBLISHED, 'publish'),
        (DRAFT, 'draft'),
    ]
    title = models.CharField(max_length=200, verbose_name=("title"))
    slug = models.SlugField(blank=True)
    bodytext = models.TextField(verbose_name=("message"))
    pic = models.ImageField("image", upload_to='uploads', height_field=None, width_field=None, max_length=None, blank=True, null=True)
    category = models.ManyToManyField(Category, verbose_name='category of this post')
    tag = models.ManyToManyField(Tag, verbose_name=("tags of this post"), blank=True, null=True)
    likes = models.ManyToManyField(User, verbose_name=("likes on post"), related_name= 'blog_posts')
    post_date = models.DateTimeField(
        auto_now_add=True, verbose_name="post date")
    modified = models.DateTimeField(null=True, verbose_name=("modified"), blank=True)
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                                  verbose_name=("posted by"),
                                  on_delete=models.SET_NULL)

    allow_comments = models.BooleanField(
        default=True, verbose_name=("allow comments"))
    comment_count = models.IntegerField(
        blank=True, default=0, verbose_name=('comment count'))
    status= models.CharField('status of post', max_length=3, choices=STATUS, default=PUBLISHED)

    objects= models.Manager()
    published= PublishedManager()
    draft= DraftManager()

    class Meta:
        verbose_name = ('post')
        verbose_name_plural = ('posts')
        ordering = ['-post_date']

    def total_likes(self):
        return self.likes.count()

    # override the save method for store unique slug
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.title))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    # a method that give us slug for linking detail of post instance
    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug,
        }

        return reverse('post_detail', kwargs=kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User, verbose_name=("name of user"), on_delete=models.SET_NULL, null=True, blank=True)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, verbose_name=("likes on post"), related_name= 'blog_comments')

    class Meta:
        ordering = ('created',)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

    # Hear a signal to save count of comment





post_save.connect(save_comment, sender=Comment)

Hw/MIni_Project_1/weblog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.forms import fields


from .models import *

class CategoryForm(forms.ModelForm):
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput(attrs={'value': 'c'}), label="Leave empty")

    class Meta:
        model = Category
        fields = '__all__'


class TagForm(forms.ModelForm):
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput(attrs={'value': 't'}), label="Leave empty")

    class Meta:
        model = Tag
        fields = '__all__'



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'bodytext', 'pic', 'category', 'tag', 'status')
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email', 'body')


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email', error_messages={'exists': 'This email already exists!'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_messages['exists'])
        return self.cleaned_data['email']


def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=80)
    subject = forms.CharField(max_length=80)
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave empty", validators=[should_be_empty])


class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length= 100 ,widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(max_length= 100 ,widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(max_length= 100 ,widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')


class UserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'is_active','email')

Hw/MIni_Project_1/weblog/blog/templates/add-cat-tag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <title> Add </title>
</head>
<body>
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'post_list' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard' %}">DashBoard</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
        </li>
      </ul>
    <div class="container">
        <div class="row">
          
            <div class="col-6">
              <br>
              <div class="col-12"><button style="width: 100%;" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal2">Add</button></div>
               <br>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col"> Tags </th>
                            
                        </tr>
                    </thead>
                    {% if tags %}
                    <tbody>
                        
                            {% for tag in tags %}
                            <tr>
                                <th> <a href="{% url 'post-tag' tag.id %}" style="text-decoration: none;" !important>{{tag.name}}</a> </th>
                                <th scope="col"> <button type="button" class="btn  btn-sm btn-danger"><a href="{% url 'delete-t' id=tag.id %}" style="color:black ; text-decoration: none;" !important>Remove</a></button> </th>
                                <th scope="col"> <button type="button" class="btn  btn-sm btn-warning"><a href="{% url 'edit-t' id=tag.id %}" style="color:black ; text-decoration: none;" !important>Edit</a></button> </th>
                            </tr>
                            {% endfor %}
                        
                    </tbody>
                    {% endif %}
    
        </table>
    
            </div>
            <div class="col-6">
              <br>
              <div class="col-12">   <button style="width: 100%;" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add</button></div>
              <br>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col"> Category </th>
                            
                        </tr>
                    </thead> 
                    {% if category %}
                    <tbody>
                        
                            {% for cat in category %}
                            <tr>
                                <th> <a href="{{cat.get_absolute_url}}" style="text-decoration: none;" !important>{{cat.name}}</a></th>
                                <th scope="col"> <button type="button" class="btn btn-sm btn-danger"><a href="{% url 'delete-c' id=cat.id %}" style="color:black ;text-decoration: none;" !important>Remove</a></button> </th>
                                <th scope="col"> <button type="button" class="btn btn-sm btn-warning"><a href="{% url 'edit-c' id=cat.id %}" style="color:black ;text-decoration: none;" !important>Edit</a></button> </th>
                            </tr>
                            {% endfor %}
                    </tbody>
                    {% endif %}
    
        </table>
    
            </div>
        </div>
    </div>
 

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %}
             {% for field in catform %}
                   <div class="form-group">
                      {{ field}}
                   </div>
                   {% endfor %}
                   <div class="text-center ">
                     <button type="submit" class=" btn btn-block send-button tx-tfm">Create Your Category</button>
                  </div>
                  </form>
                
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


      <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add Tag</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %}
                {% for field in tagform %}
                   <div class="form-group">
                      {{ field}}
                   </div>
                   {% endfor %}
                   <div class="text-center ">
                    <button type="submit" class=" btn btn-block send-button tx-tfm">Create Your Tag</button>
                 </div>
                 </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


</body>
</html>

Hw/MIni_Project_1/weblog/blog/templates/add_post.html
{% extends "base_weblog.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="container">

<h1 class="text-center mt-5">New Post</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-md-6">
        
        <div class="form-group"> 
            <label for="Input">{{ form.title_label }}</label>
            {{ form.title|attr:"rows:20"|attr:"cols:20"|attr:"class:form-control"|attr:"placeholder:title"|attr:"id:Input" }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group"> 
            <label for="Input">select your image</label>
        </br>
            {{ form.pic }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group"> 
            <label for="Input">select your Categories</label>
        </br>

            {{ form.category|attr:"rows:20"|attr:"cols:20"|attr:"type:select"|attr:"class:form-control"|attr:"placeholder:description"|attr:"id:Input" }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group"> 
            <label for="Input">Status</label>
        </br>

            {{ form.status|attr:"rows:20"|attr:"cols:20"|attr:"type:select"|attr:"class:form-control"|attr:"placeholder:description"|attr:"id:Input" }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group"> 
            <label for="Input">select your Tags</label>
        </br>

            {{ form.tag|attr:"rows:20"|attr:"cols:20"|attr:"type:select"|attr:"class:form-control"|attr:"placeholder:description"|attr:"id:Input" }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>

    </div>
    <div class="col-md-6">
        <div class="form-group"> 
            <label for="Input">{{ form.bodytext_label }}</label>
            {{ form.bodytext|attr:"rows:20"|attr:"cols:20"|attr:"class:form-control"|attr:"placeholder:description"|attr:"id:Input" }}
            <small id="UserlHelp" class="form-text text-muted"></small>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</div>
{% csrf_token %}
</form>
</div>
{% endblock content %}

{% block name-side %} Categories {% endblock name-side %}

{% block sidebar %}
  {% for cat in category %}
    <div style="background: #344; min-height: 0; margin: 10px auto; padding: 30px 10px; text-align: center; color: #FFF;" !important> <a href="{{cat.get_absolute_url}}" style="color: white;;  text-decoration: none;" !important>{{cat.name}}</a></div>
  {% endfor %}
{% endblock sidebar %}

Hw/MIni_Project_1/weblog/blog/templates/all_post.html
{% extends "base_weblog.html" %}
{% block title %}
Posts
{% endblock title %}
{% block content %}
        <article>
           <h2>Posts : </h2>
				</article>
          {% for post in post_list %}

        <article>
					<h2>{{post.title}}</h2>
          <br>
          <p>Written by : <b>{{post.posted_by}}</b> on <b>{{post.post_date}}</b></p>
          <br>
          <br>
					<p>{{ post.bodytext|truncatewords:20 }}</p>
          <br>
          <p><a href={{ post.get_absolute_url }}>read more</a></p>
				</article>
                               




          {% endfor %}

{% endblock content %}

{% block name-side %} Categories {% endblock name-side %}

{% block sidebar %}
  {% for cat in category %}
    <div style="background: #344; min-height: 0; margin: 10px auto; padding: 30px 10px; text-align: center; color: #FFF;" !important> <a href="{{cat.get_absolute_url}}" style="color: white;;  text-decoration: none;" !important>{{cat.name}}</a></div>
  {% endfor %}
{% endblock sidebar %}

Hw/MIni_Project_1/weblog/blog/templates/contact.html
{% extends "base_account.html" %}
{% block content %}

<style>
        .container{
             padding-top: 15px;
        }

    #id_name{
        width:100%
        }

    #id_message{
        width:100%
        }

    #id_email{
        width:100%
        }
</style>

<div class="container ">
    <h2>Send Me a Message</h2>
    <form action="" method="POST">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label_tag }}</label>
            <p>{{ field }}</p>
        </div>
        {% endfor %}
        <button type="reset" class="btn btn-secondary">Reset</button>
         <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>


{% endblock content %}

Hw/MIni_Project_1/weblog/blog/templates/dashboard.html
{% extends "base_weblog.html" %}
{% block title %}
DashBoard
{% endblock title %}
{% block content %}

        <article>
           <h4> Welcome Dear {{user.username}}</h4>
           <br><br>
            <p style="float-right"><a href="{% url 'new_post' %}">new post</a></p>
            <br><br>
            <p style="float-right"><a href="{% url 'edit_profile' %}">Edit Profile</a></p>
            <br><br>
            <p style="float-right"><a href="{% url 'add-cat-tag' %}">Add Category/Tag</a></p>
            <br><br>
           <h2>Posts : </h2>
           {% if posts_published %}
				</article>
          {% for post in posts_published %}

        <article>
					<h2>{{post.title}}</h2>
          <br>
          <p>Written by : <b>{{post.posted_by}}</b> on <b>{{post.post_date}}</b></p>
          <br>
          <br>
					<p>{{ post.bodytext|truncatewords:20 }}</p>
          <br>
          <p><a href={{ post.get_absolute_url }}>read more</a></p>
				</article>
        {% endfor %}
        {% else %}
          <article>
              <h2> You Don't any post to show :/ </h2>
          </article>
          <article>
              <div class="col-6"></div>
              <button class="btn btn-success"><a href="{% url 'add_post' %}">Create Post</a></button>
          </article>
          {% endif %}
        <br><br>
        <h2>Draft Posts : </h2>
        {% if posts_draft %}
     </article>
       {% for post in posts_draft %}

     <article>
       <h2>{{post.title}}</h2>
       <br>
       <p>Written by : <b>{{post.posted_by}}</b> on <b>{{post.post_date}}</b></p>
       <br>
       <br>
       <p>{{ post.bodytext|truncatewords:20 }}</p>
       <br>
       <p><a href={{ post.get_absolute_url }}>read more</a></p>
     </article>                             
          {% endfor %}

{% else %}
<article>
    <h2> You Don't any post to show :/ </h2>
</article>
{% endif %}
{% endblock content %}

{% block name-side %} Categories {% endblock name-side %}

{% block sidebar %}
  {% for cat in category %}
    <div style="background: #344; min-height: 0; margin: 10px auto; padding: 30px 10px; text-align: center; color: #FFF;" !important> <a href="{{cat.get_absolute_url}}" style="color: white;;  text-decoration: none;" !important>{{cat.name}}</a></div>
  {% endfor %}
{% endblock sidebar %}

Hw/MIni_Project_1/weblog/blog/templates/delete-c.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <title> Add </title>
</head>
<body>
    <div class="row text-center">
        <div class="col-md-12 mt-5 mb-5 pb-5">
            <div style="box-shadow: 10px 10px 5px grey;" class="shadow-box-example hoverable flex-center">
                <p class="white-text">Are you sure delete this Category : <b>{{ category.name}}</b> </p>
                <form action="" method="POST">
                    {% csrf_token %}
                   <div class="text-center ">
                     <button type="submit" class=" btn btn-danger send-button tx-tfm">DELETE</button>
                  </div>
                  <div class="text-center mt-3">
                    <button type="button" class="btn btn-sm btn-danger"><a href="{% url 'add-cat-tag' %}" style="color:black ;text-decoration: none;" !important>Cancel</a></button>
                 </div>
                  </form>
            </div>
        </div>
    </div>
</body>
</html>

Hw/MIni_Project_1/weblog/blog/templates/delete-post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
    <title> Add </title>
</head>
<body>
    <div class="row text-center">
        <div class="col-md-12 mt-5 mb-5 pb-5">
            <div style="box-shadow: 10px 10px 5px grey;" class="shadow-box-example hoverable flex-center">
                <p class="white-text">Are you sure delete this Post : <b>{{ post.title}}</b> </p>
                <form action="" method="POST">
                    {% csrf_token %}
                   <div class="text-center ">
                     <button type="submit" class=" btn btn-danger send-button tx-tfm">DELETE</button>
                  </div>
                  <div class="text-center mt-3">
                    <button type="button" class="btn btn-sm btn-danger"><a href="{% url 'post_detail' slug=post.slug %}" style="color:black ;text-decoration: none;" !important>Cancel</a></button>
                 </div>
                  </form>
            </div>
        </div>
    </div>
</body>
</html>

Hw/MIni_Project_1/weblog/blog/templates/tag.html
{% extends "base_weblog.html" %}
{% block title %}
Posts
{% endblock title %}
{% block content %}
        <article>
           <h2>{{tag.name}} : </h2>
				</article>
          {% for post in tag.post_set.all %}

        <article>
					<h2>{{post.title}}</h2>
          <br>
          <p>Written by : <b>{{post.posted_by}}</b> on <b>{{post.post_date}}</b></p>
          <br>
          <br>
					<p>{{ post.bodytext|truncatewords:20 }}</p>
          <br>
          <p><a href={{ post.get_absolute_url }}>read more</a></p>
				</article>
                               




          {% endfor %}

{% endblock content %}

{% block name-side %} Tags {% endblock name-side %}

{% block sidebar %}
  {% for t in tag_all %}
    <div style="background: #344; min-height: 0; margin: 10px auto; padding: 30px 10px; text-align: center; color: #FFF;" !important> <a href="{% url 'post-tag' t.id %}" style="color: white;;  text-decoration: none;" !important>{{t.name}}</a></div>
  {% endfor %}
{% endblock sidebar %}